services:
  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - ./scripts:/scripts
      - cassandra_data:/var/lib/cassandra
    environment:
      CASSANDRA_ENABLE_MATERIALIZED_VIEWS: "true"
      CASSANDRA_CLUSTER_NAME: "MyCluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_RACK: "rack1"
      MAX_HEAP_SIZE: "1G"
      HEAP_NEWSIZE: "256M"
      # Configuración simplificada para Cassandra 4.1+
      JVM_OPTS: "-Xms1G -Xmx1G"
    mem_limit: 2g
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 20s
      timeout: 10s
      retries: 15

volumes:
  cassandra_data:
